# Generated by Django 5.0.1 on 2024-01-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_alter_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='website',
        ),
    ]
